var playerCardArray = [[0,0,"",""], [0,0,"",""], [0,0,"",""]];
var opponentCardArray = [[0,0,"",""], [0,0,"",""], [0,0,"",""]];
var playerHealth = 40;
var opponentHealth = 40;


//display elements:
var playerHealthDisp;
var opponentHealthDisp;
var attackValues;
var defenseValues;
var titles;

function getRandomImage() {  
    //declare an array to store the images  
    var randomImage = new Array();  
    
    //insert the URL of images in array  
    randomImage[0] = "pandaberserker.png";  
    randomImage[1] = "pandacommander.png";  
    randomImage[2] = "pandaeating.png";  
    randomImage[3] = "pandaguerilla.png";  
    randomImage[4] = "pandagunner.png";  
    randomImage[5] = "pandama.png"; 
    randomImage[6] = "pandasleepy.png"; 
    randomImage[7] = "pandasneaky.png";
        
    //generate a number and provide to the image to generate randomly 
    //return the images generated by a random number  
    var number = Math.floor(Math.random()*randomImage.length);  
    console.log=("Is this working?");  
    document.getElementById("randomImage0").src=randomImage[number];
    number = Math.floor(Math.random()*randomImage.length);
    document.getElementById("randomImage1").src=randomImage[number];
    number = Math.floor(Math.random()*randomImage.length);
    document.getElementById("randomImage2").src=randomImage[number];
    number = Math.floor(Math.random()*randomImage.length);
    document.getElementById("randomImage3").src=randomImage[number];
    number = Math.floor(Math.random()*randomImage.length);
    document.getElementById("randomImage4").src=randomImage[number];
    number = Math.floor(Math.random()*randomImage.length);
    document.getElementById("randomImage5").src=randomImage[number];  
    }  

function initGame() {
    playerHealthDisp = document.getElementById('player-health');
    opponentHealthDisp = document.getElementById('opponent-health');
    
    titles = document.getElementsByClassName('card-title');
    attackValues = document.getElementsByClassName('attack');
    defenseValues = document.getElementsByClassName('defense');

    for (let i = 0; i< attackValues.length; i++) {
        var attackVal = parseInt(Math.random() * 4 + 2);
        var healthVal = parseInt(Math.random() * 10 + 20);
        if (i < 3) {
            opponentCardArray[i][0] = attackVal;
            opponentCardArray[i][1] = healthVal;

        }
        else {
            playerCardArray[i-3][0] = attackVal;
            playerCardArray[i-3][1] = healthVal;

            console.log("i is: " + i + " " +playerCardArray[i-3][2]);
        }
    } 
    getRandomImage();
    updateDisplay();
}
function aiChoice() {
    //power up creature
    //play spell
    var choice = parseInt(Math.random() * 2 + 1);
     {
        if (choice == 0) {
            //strategy power up 30% chance
        }
        else {
            //strategy spell 60%
        }
    }
}
function updateDisplay() {
    //update player and opponent health:
    playerHealthDisp.innerHTML = "Player Health: " + playerHealth;
    opponentHealthDisp.innerHTML = "Opponent Health: " + opponentHealth;
    var AIChoice = aiChoice();

    for (let i = 0; i< attackValues.length; i++) {
       
        if (i < 3) {
            attackValues[i].innerHTML = "Attack: " + opponentCardArray[i][0];
            defenseValues[i].innerHTML = "Health: " + opponentCardArray[i][1];
            titles[i].innerHTML = opponentCardArray[i][2];
        }
        else {
            attackValues[i].innerHTML = "Attack: " + playerCardArray[i-3][0];
            defenseValues[i].innerHTML = "Health: " + playerCardArray[i-3][1]; 

            titles[i].innerHTML = playerCardArray[i-3][2];
        }
    } 
}
function cardDeathMatch() {
    //1. go through all player cards and all enemy cards
        for (let i = 0; i< playerCardArray.length; i++) {

            //Willy: Added Two if statements that check if each cards health is >= 1 before calculating damage.
            if(opponentCardArray[i][1] >= 1){
                playerCardArray[i][1] -= opponentCardArray[i][0];
            }
            if(playerCardArray[i][1] >= 1){
                opponentCardArray[i][1] -= playerCardArray[i][0]; 
            }        
            
            
            if (opponentCardArray[i][1]<1) {
                if (opponentCardArray[i][2] == "Dead") {
                    opponentHealth -= playerCardArray[i][0];
                    opponentCardArray[i][1] = 0;
                }
                opponentCardArray[i][2] = "Dead";
            }
            if(playerCardArray[i][1] < 1) {
                if (playerCardArray[i][2] == "Dead") {
                    playerHealth -= opponentCardArray[i][0];
                    playerCardArray[i][1] = 0;
                }
                playerCardArray[i][2] = "Dead";
            }
    

            

            /*Willy's addition: If Player card array at index 1(health) is below 1 (dead) then set that cards attack to 0 so it's no longer calculating damage*/
           /* if (playerCardArray[i][1] < 1){
                playerCardArray[i][0] = 0;
            } */
/*Willy's addition: If oppoennt card array at index 1(health) is below 1 (dead) then set that cards attack to 0 so it's no longer calculating damage*/
 
/* if (opponentCardArray[i][1] <1){
                opponentCardArray[i][0] = 0;
            } */
            //commented out above code for the for loop iteration instead. Left this example in as another possible solution (less clean)
            

            checkGameOver();
            updateDisplay();
        }
}
function checkGameOver() {
    if (playerHealth < 1 && opponentHealth < 1) {
        alert("It was a tie");
    }
    else if (playerHealth < 1) {
        alert("You lost");
    }
    else if (opponentHealth < 1) {
        alert("You won");
    }
}
initGame();
